server:
  port: 8083
  
spring:
  application:
    name:  simpsons
  profiles:
    active: 'local'
    
data:
  folder: classpath:./data
  characters: characters.json
  phrases: phrases.json
  
#ENDPOINTS:
management:
  endpoints:
    web:
      exposure:
        include:
        - 'health'
        - 'info'